In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow.keras import datasets, layers, models

In [2]:
(x_train,y_train),(x_test,y_test) = datasets.cifar10.load_data()

In [3]:
x_train.shape

(50000, 32, 32, 3)

In [4]:
x_test.shape

(10000, 32, 32, 3)

In [5]:
x_train[0]

array([[[ 59,  62,  63],
        [ 43,  46,  45],
        [ 50,  48,  43],
        ...,
        [158, 132, 108],
        [152, 125, 102],
        [148, 124, 103]],

       [[ 16,  20,  20],
        [  0,   0,   0],
        [ 18,   8,   0],
        ...,
        [123,  88,  55],
        [119,  83,  50],
        [122,  87,  57]],

       [[ 25,  24,  21],
        [ 16,   7,   0],
        [ 49,  27,   8],
        ...,
        [118,  84,  50],
        [120,  84,  50],
        [109,  73,  42]],

       ...,

       [[208, 170,  96],
        [201, 153,  34],
        [198, 161,  26],
        ...,
        [160, 133,  70],
        [ 56,  31,   7],
        [ 53,  34,  20]],

       [[180, 139,  96],
        [173, 123,  42],
        [186, 144,  30],
        ...,
        [184, 148,  94],
        [ 97,  62,  34],
        [ 83,  53,  34]],

       [[177, 144, 116],
        [168, 129,  94],
        [179, 142,  87],
        ...,
        [216, 184, 140],
        [151, 118,  84],
        [123,  92,  72]]

In [6]:
x_train=x_train/255
x_test=x_test/255

In [7]:
x_train[0]

array([[[0.23137255, 0.24313725, 0.24705882],
        [0.16862745, 0.18039216, 0.17647059],
        [0.19607843, 0.18823529, 0.16862745],
        ...,
        [0.61960784, 0.51764706, 0.42352941],
        [0.59607843, 0.49019608, 0.4       ],
        [0.58039216, 0.48627451, 0.40392157]],

       [[0.0627451 , 0.07843137, 0.07843137],
        [0.        , 0.        , 0.        ],
        [0.07058824, 0.03137255, 0.        ],
        ...,
        [0.48235294, 0.34509804, 0.21568627],
        [0.46666667, 0.3254902 , 0.19607843],
        [0.47843137, 0.34117647, 0.22352941]],

       [[0.09803922, 0.09411765, 0.08235294],
        [0.0627451 , 0.02745098, 0.        ],
        [0.19215686, 0.10588235, 0.03137255],
        ...,
        [0.4627451 , 0.32941176, 0.19607843],
        [0.47058824, 0.32941176, 0.19607843],
        [0.42745098, 0.28627451, 0.16470588]],

       ...,

       [[0.81568627, 0.66666667, 0.37647059],
        [0.78823529, 0.6       , 0.13333333],
        [0.77647059, 0

In [8]:
y_train

array([[6],
       [9],
       [9],
       ...,
       [9],
       [1],
       [1]], dtype=uint8)

In [9]:
early_stopping = tf.keras.callbacks.EarlyStopping(
    monitor='val_loss',   # Stop when validation loss stops improving
    patience=3,           # Number of epochs to wait before stopping
    restore_best_weights=True  # Restore the best model weights
)

In [10]:
cnn = models.Sequential([
    layers.Conv2D(64, (3,3), activation='relu', padding='same', input_shape=(32,32,3)),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(128, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(256, (3,3), activation='relu', padding='same'),
    layers.BatchNormalization(),
    layers.MaxPooling2D((2,2)),
    layers.Dropout(0.3),

    layers.Flatten(),
    layers.Dense(512, activation='relu'),
    layers.BatchNormalization(),
    layers.Dropout(0.5),

    layers.Dense(10, activation='softmax')
])


c:\Users\abhis\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [ ]:
cnn.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'],)

In [ ]:
cnn.fit(x_train,y_train,epochs=50,batch_size=64,callbacks=[early_stopping])  #initail traning accuracy 88.80, 2nd iteration 69.93

Epoch 1/50
782/782 ━━━━━━━━━━━━━━━━━━━━ 173s 213ms/step - accuracy: 0.4435 - loss: 1.8174
Epoch 2/50
  1/782 ━━━━━━━━━━━━━━━━━━━━ 1:48 139ms/step - accuracy: 0.6250 - loss: 0.9285

c:\Users\abhis\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\callbacks\early_stopping.py:155: UserWarning: Early stopping conditioned on metric `val_loss` which is not available. Available metrics are: accuracy,loss
  current = self.get_monitor_value(logs)


782/782 ━━━━━━━━━━━━━━━━━━━━ 83s 106ms/step - accuracy: 0.6711 - loss: 0.9338
Epoch 3/50
782/782 ━━━━━━━━━━━━━━━━━━━━ 84s 107ms/step - accuracy: 0.7378 - loss: 0.7610
Epoch 4/50
782/782 ━━━━━━━━━━━━━━━━━━━━ 83s 106ms/step - accuracy: 0.7699 - loss: 0.6624
Epoch 5/50
782/782 ━━━━━━━━━━━━━━━━━━━━ 82s 105ms/step - accuracy: 0.7982 - loss: 0.5739
Epoch 6/50
308/782 ━━━━━━━━━━━━━━━━━━━━ 50s 107ms/step - accuracy: 0.8309 - loss: 0.4809

KeyboardInterrupt: 

In [13]:
cnn.evaluate(x_test,y_test)  #without dropuout the accuracy was 67.36,2nd iteration 67.94,

313/313 ━━━━━━━━━━━━━━━━━━━━ 5s 14ms/step - accuracy: 0.7093 - loss: 0.8702


[0.865003228187561, 0.7077999711036682]

In [ ]:
from sklearn.metrics import classification_report

In [ ]:
y_pred=cnn.predict(x_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step


In [ ]:
from sklearn.metrics import classification_report

# Predict labels for test data
y_pred = cnn.predict(x_test)  # Get model predictions

# Convert predictions to class labels (if using softmax or sigmoid)
y_pred_labels = np.argmax(y_pred, axis=1)  # For multi-class classification
# y_pred_labels = (y_pred > 0.5).astype(int)  # For binary classification

# Print classification report
print(classification_report(y_test, y_pred_labels))


313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step
              precision    recall  f1-score   support

           0       0.69      0.69      0.69      1000
           1       0.88      0.73      0.80      1000
           2       0.58      0.36      0.45      1000
           3       0.37      0.49      0.42      1000
           4       0.54      0.61      0.57      1000
           5       0.60      0.53      0.57      1000
           6       0.74      0.75      0.75      1000
           7       0.75      0.72      0.74      1000
           8       0.75      0.81      0.78      1000
           9       0.70      0.80      0.75      1000

    accuracy                           0.65     10000
   macro avg       0.66      0.65      0.65     10000
weighted avg       0.66      0.65      0.65     10000

